Becklyn/RadBundle

- Entity/Extension/EntityId.php
> Add default id entity property trait

- Entity/Extension/EntityTimestamps.php
- 2 empty lines after usestatement
- No empty line after variable typedefinition
> Change CodeStyling for more consistency

- Entity/SortableEntity.php
The declaration of setSortOrder must be compatible with the declaration in SortOrderTrait
> Update SortableEntity with php7 type declaration

- Model/SortableHandler.php
* Add correct IS NULL query part if the value is null
> Fix SortableHandler bug if the value in the where clause is null

- Entity/Traits/TimestampsTrait.php
> Revert PR #26 again since Doctrine can’t convert a \DateTime to a \DateTimeImmutable

- Resources/config/services.yml
- Service/SimpleRouteVoter.php
The ContainerAware class does not exist anymore so we use dependency injection instead
> Remove ContainerAware and use request stack instaead

- CHANGELOG.md
- UPGRADE.md
- src/BecklynRadBundle.php
- src/Bundle/BundleExtension.php
- src/Model/Model.php
| New feature?  | yes 
| Docs PR       | **missing** 
Re-adds the bundle extension
> Re-add simplified bundle extension

- src/Exception/LabeledEntityRemovalBlockedException.php
> Provide autocompletion in PhpStorm

- CHANGELOG.md
- src/Integration/Profiler.php
| Bug fix?      |no
| Improvement?  | yes
Adds a convenience wrapper to disable the profiler.
> Add profiler wrapper

- CHANGELOG.md
- composer.json
- src/Twig/RadTwigExtension.php
- tests/Twig/RadTwigExtensionTest.php
MAYD-325
| New feature?  | yes
> Data Container

- CHANGELOG.md
- src/Controller/DownloadableStringTrait.php
MAYD-333
| New feature?  | yes 
> Add trait to have downloadable strings

- CHANGELOG.md
- src/Form/Extension/ChoicePlaceholderFormExtension.php
> Add ChoicePlaceholderFormExtension

- CHANGELOG.md
- src/Model/Model.php
- src/Model/ModelInterface.php
> Add model interface

- composer.json
- src/Form/FormErrorMapper.php
| Bug fix?      | yes
| Improvement?  | yes  
| BC breaks?    | theoretically yes, but not for the current required Symfony version
| Docs PR       | **missing**
> Translator deprecation

- CHANGELOG.md
- src/Resources/views/form/theme.html.twig
> Add default form theme

- CHANGELOG.md
- src/Controller/BaseController.php
- src/Stats/StatsCounter.php
- tests/Stats/StatsCounterTest.php
| New feature?  | yes
| Docs PR       | **missing** 
Added a `StatsCounter`
> Stats counter

- CHANGELOG.md
- UPGRADE.md
- src/Pagination/Data/PaginatedList.php
- src/Pagination/Data/Pagination.php
- src/Pagination/Pagination.php
- src/Pagination/Paginator.php
- src/Resources/config/services.yaml
- tests/Pagination/Data/PaginatedListTest.php
- tests/Pagination/Data/PaginationTest.php
| New feature?  | yes
As it turns out, the implementation is way more easy than I previously thought / implemented it... Oops.
Sort-of a BC break in the `Pagination`, fixed by changing the namespace.
> Add Paginator + paginated results

- src/Pagination/Data/Pagination.php
- tests/Pagination/Data/PaginationTest.php
| Bug fix?      | yes
| Docs PR       | not needed
Oops.
> Fix invalid constructor args + add regression test

- src/Model/Model.php
| Bug fix?      | yes
Removed usage of an interface that will be removed in Sf 5 and deprecated in Sf 4.4+
> Remove future deprecation

- CHANGELOG.md
- src/Html/DataContainer.php
- src/Twig/RadTwigExtension.php
- tests/Html/DataContainerTest.php
- tests/Twig/RadTwigExtensionTest.php
| New feature?  | yes                   |
See the changelog on "why"
> Extract data container into an own class

- CHANGELOG.md
- src/Resources/translations/messages+intl-icu.de.yaml
- src/Resources/translations/messages+intl-icu.en.yaml
- src/Resources/views/form/theme.html.twig
| Improvement?  | yes    |
| Docs PR       |  —                                   |
> Form polish

- CHANGELOG.md
- src/Pagination/Data/PaginatedList.php
- tests/Pagination/Data/PaginatedListTest.php
> Add PaginatedList::createFromArray

- CHANGELOG.md
- src/Controller/BaseController.php
> Fix trans domain for `getEntityRemovalMessage()`

- CHANGELOG.md
- phpunit.xml
- src/Exception/EntityRemovalBlockedException.php
- src/Exception/InvalidSortOperationException.php
- src/Exception/RadException.php
- src/Model/Model.php
- src/Model/ModelInterface.php
- src/Sortable/SortableHandler.php
- tests/Sortable/SortableHandlerTest.php
| New feature?  | yes                   |
> Sortable handler + base exception + fluent method models

- CHANGELOG.md
- src/Controller/BaseController.php
| Bug fix?      | /no                                                                |
> Improve handling of entity removal blocked exceptions

- CHANGELOG.md
- src/Resources/views/form/theme.html.twig
> Add form-widget-nested class

- .travis.yml
- composer.json
- src/Bundle/BundleExtension.php
- src/Controller/BaseController.php
- src/Controller/DownloadableStringTrait.php
- src/Entity/Interfaces/EntityInterface.php
- src/Entity/Interfaces/SortableEntityInterface.php
- src/Entity/Traits/IdTrait.php
- src/Entity/Traits/SortOrderTrait.php
- src/Entity/Traits/TimestampsTrait.php
- src/Exception/EntityRemovalBlockedException.php
- src/Exception/LabeledEntityRemovalBlockedException.php
- src/Exception/RadException.php
- src/Form/FormErrorMapper.php
- src/Html/DataContainer.php
- src/Model/Model.php
- src/Model/ModelInterface.php
- src/Pagination/Data/PaginatedList.php
- src/Pagination/Data/Pagination.php
- src/Pagination/Paginator.php
- src/Path/PathHelper.php
- src/Sortable/SortableHandler.php
- src/Stats/StatsCounter.php
- src/Twig/RadTwigExtension.php
> Support symfony 5

- .gitignore
- .travis.yml
- composer.json
- vendor-bin/test/composer.json
> Use new structure for CI

- CHANGELOG.md
- src/Bundle/BundleExtension.php
> Support the new bundle file structure

- Entity/Traits/SortOrderTrait.php
> Fix types in sort order trait

- CHANGELOG.md
- composer.json
- src/Model/Model.php
> Don't use deprecated `ManagerRegistry`

- CHANGELOG.md
- src/Pagination/Data/Pagination.php
- tests/Pagination/Data/PaginationTest.php
> Add `total` to the normalized pagination data.

- CHANGELOG.md
- src/Pagination/Data/Pagination.php
- tests/Pagination/Data/PaginationTest.php
> Fix invalid calulcations in pagination

- CHANGELOG.md
- src/Usages/Data/EntityUsage.php
- src/Usages/Data/ResolvedEntityUsage.php
- src/Usages/EntityUsagesFinder.php
All these were not really used in the wild, so no BC adaptions here.
> Refactor and improve entity usage implementation

- CHANGELOG.md
- src/Usages/Data/EntityUsage.php
- src/Usages/Data/ResolvedEntityUsage.php
| Deprecations? | /no     |
All these were not really used in the wild, so no BC adaptions here.
> Added `type` to entity usages.

- CHANGELOG.md
- src/Exception/InvalidRouteActionException.php
- src/Exception/InvalidTranslationActionException.php
- src/Route/DeferredRoute.php
- src/Translation/DeferredTranslation.php
- tests/Route/DeferredRouteTest.php
- tests/Translation/DeferredTranslationTest.php
- vendor-bin/test/composer.json
> DeferredTranslation + DeferredRoute improvements

- CHANGELOG.md
- src/Resources/views/form/theme.html.twig
> Don’t use <label> as most outer element in forms

- CHANGELOG.md
- src/Resources/views/form/theme.html.twig
> Fix missed form theme change

- CHANGELOG.md
- src/Resources/views/form/theme.html.twig
> Make nested form rendering more robust and more flexible.

- .travis.yml
- CHANGELOG.md
- composer.json
- src/Pagination/Data/PaginatedList.php
- src/Sortable/PropertiesSortableHandler.php
- src/Sortable/SortableHandler.php
- tests/Sortable/PropertiesSortableHandlerTest.php
- tests/Sortable/SortableHandlerTest.php
- tests/Sortable/SortableTestTrait.php
> Sortable bug fixes + PropertiesSortableHandler

- CHANGELOG.md
- src/Command/CommandHelper.php
- src/Exception/RadExceptionInterface.php
- src/Exception/TagNormalizationException.php
- src/Tags/TagHelper.php
- src/Tags/TagInterface.php
> CommandHelper + Tags infrastructure

- .gitignore
- CHANGELOG.md
- src/Pagination/Data/Pagination.php
- tests/Pagination/Data/PaginationTest.php
> Add `Pagination::isValid()`

- .travis.yml
- CHANGELOG.md
- phpstan.neon
- src/Command/CommandHelper.php
- src/Resources/config/services.yaml
> Add `CommandHelper::disableSearchIndexing()`

- CHANGELOG.md
- UPGRADE.md
- src/Stats/StatsCounter.php
- src/Translation/DeferredTranslation.php
- src/Usages/Data/EntityUsage.php
- src/Usages/Data/ResolvedEntityUsage.php
- src/Usages/EntityUsagesFinder.php
- src/Usages/EntityUsagesProviderInterface.php
> Several improvements + deprecate entity usages

- CHANGELOG.md
- UPGRADE.md
- src/Stats/NestedStatsCounter.php
- src/Stats/StatsCounter.php
- src/Stats/StatsCounterInterface.php
- vendor-bin/test/composer.json
> StatsCounter improvements: nested + log levels

- CHANGELOG.md
- src/Search/SimpleEntitySearchHelper.php
- src/Search/SimpleQueryTokenizer.php
- tests/Search/SimpleQueryTokenizerTest.php
> Add `SimpleEntitySearchHelper + prefix-based query tokenizer

- CHANGELOG.md
- src/Controller/BaseController.php
| BC breaks?    |no                                                                |
| New feature?  |no                    |
| Improvement?  |no     |
| Bug fix?      | yes                                                               |
| Deprecations? |no     |
> Add meta PhpDoc comments to let PhpStorm know about the translation key + domain

- .travis.yml
- CHANGELOG.md
- composer.json
- src/Controller/BaseController.php
| BC breaks?    |no                                                                |
| New feature?  |no                    |
| Improvement?  |no     |
| Bug fix?      |no                                                                |
| Deprecations? |no     |
- Add `BaseController::getLogger`
- Add `BaseController::getJsonRequestData`
- Require at least PHP 7.3
> Extend BaseController

- CHANGELOG.md
- src/Controller/BaseController.php
| BC breaks?    |no                                                                |
| New feature?  |no                    |
| Improvement?  |no     |
| Bug fix?      | yes                                                               |
| Deprecations? |no     |
> Remove return type to fix BC

- CHANGELOG.md
- src/Exception/ExceptionWithFrontendLabelTrait.php
- src/Exception/UnexpectedTypeException.php
> Add `ExceptionWithFrontendLabelTrait` + `UnexpectedTypeException`

- CHANGELOG.md
- src/Ajax/AjaxResponseBuilder.php
- src/Exception/LabeledExceptionTrait.php
- tests/Ajax/AjaxResponseBuilderTest.php
> Quality of life improvements

- .github/CODEOWNERS
- CHANGELOG.md
- src/Controller/BaseController.php
> Simplify signature of `BaseController::ajaxResponse()`
